name: dwarfurl
description: This is a link shrinker that works using firebase

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.12.0
  cloud_firestore: ^3.1.8
  flutter_svg: ^1.0.3
  google_fonts: ^2.3.1
  provider: ^6.0.2
  regexpattern: ^2.0.1
  avatar_glow: ^2.0.2
  clipboard: ^0.1.3
  auto_size_text: ^3.0.0
  animations: ^2.0.2
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.0.4

flutter_native_splash:
  image_path: "assets/images/logo.png"
  color: "#FFFFFF"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
