name: dwarfurl
description: This is a link shrinker that works using firebase

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.9.0
  cloud_firestore: ^4.5.0
  flutter_svg: ^2.0.4
  google_fonts: ^4.0.3
  provider: ^6.0.2
  avatar_glow: ^2.0.2
  clipboard: ^0.1.3
  animations: ^2.0.2
  url_launcher: ^6.0.20
  package_info_plus: ^3.0.3
  string_validator: ^1.0.0
  url_strategy: ^0.2.0
  dio: ^5.1.1
  firebase_dynamic_links: ^5.1.0  
  logger: ^1.3.0
  flutter_gen_runner: ^5.2.0
  flutter_dotenv: ^5.0.2
  injectable: ^2.1.1
  get_it: ^7.2.0
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.0.4
  change_app_package_name: ^1.0.0
  build_runner: ^2.3.3
  injectable_generator: ^2.1.5

flutter_gen:
  integrations:
    flutter_svg: true

flutter_native_splash:
  web: true
  image: "assets/images/logo.png"
  color: "#FFFFFF"
  color_dark: "#1b1b1b"

flutter:
  uses-material-design: true

  fonts: 
    - family: Product Sans
      fonts:
        - asset: assets/fonts/Product-Sans-Regular.ttf

  assets:
    - .env
    - assets/images/
