// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkayZiTjIw6CWpgMmQHaHlR52vWE1a9Rc',
    appId: '1:764018160681:web:10d4b4a609019ea47cd838',
    messagingSenderId: '764018160681',
    projectId: 'dwarfurl',
    authDomain: 'dwarfurl.firebaseapp.com',
    storageBucket: 'dwarfurl.appspot.com',
    measurementId: 'G-D7R3KH7MPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClHPVQhF2W8fzLsKWPGVdO61WqqXDb_5Y',
    appId: '1:764018160681:android:08eb646a145e750e7cd838',
    messagingSenderId: '764018160681',
    projectId: 'dwarfurl',
    storageBucket: 'dwarfurl.appspot.com',
  );
}
